### ISSUE TITLE
Attempt to run board flasher under nix shell results in openocd error

### ISSUE THREAD

**Issue by forGGe** [forGGe/theCore#190]
Log as follows:

```
$ ~/projects/thecore/core/scripts/flasher.py -l suite_list.txt -b ~/projects/thecore/core/scripts/connected_devices_example.json 
Found suite: platform_bat target: tivac_tm4
Found suite: platform_bat target: stm32f4discovery_simple
Found suite: platform_bat target: stm32f4discovery_simple
Found suite: unity_demo target: stm32f4discovery_simple
Found suite: unity_demo target: tivac_tm4
Board is probably connected: tivac_tm4 debugger: openocd
Board is probably connected: stm32f4discovery_simple debugger: openocd
Suite: platform_bat is ready to be uploaded to tivac_tm4. Proceed? [y/N/a]: y
['openocd', '-f', 'ek-lm4f120xl.cfg', '-c', 'init; reset halt; wait_halt; flash write_image erase /tmp/build_tests/tivac_tm4/platform_bat.gnu//build/platform_bat; reset run; shutdown']
Traceback (most recent call last):
  File "/home/executor/projects/thecore/core/scripts/flasher.py", line 80, in <module>
    flash_executors[debugger](suite_data = row, board_data = board_data)
  File "/home/executor/projects/thecore/core/scripts/flasher.py", line 35, in do_openocd_flash
    subprocess.run(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'openocd'
```

**Comment by forGGe** [comment]
Addressed in #193
